# --------------------------------------------------------------------------------------------------
# powerlevel10k instant prompt
# --------------------------------------------------------------------------------------------------
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --------------------------------------------------------------------------------------------------
# environment
# --------------------------------------------------------------------------------------------------
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

typeset -U path PATH
path=("$HOME/.local/bin" "${path[@]}")
fpath+=("$HOME/.config/zsh/functions")

export PROJECTS="$HOME/projects"

export ZIM_HOME="$HOME/.zim"

export OPENCODE_ENABLE_EXA=true
export OPENCODE_EXPERIMENTAL_LSP_TOOL=true
export OPENCODE_EXPERIMENTAL_OXFMT=true

export PNPM_HOME="$HOME/Library/pnpm"
path+=("$PNPM_HOME")

# --------------------------------------------------------------------------------------------------
# homebrew
# --------------------------------------------------------------------------------------------------
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  export HOMEBREW_AUTO_UPDATE_SECS=86400
fi

# --------------------------------------------------------------------------------------------------
# zimfw
# --------------------------------------------------------------------------------------------------
zstyle ':zim:zmodule' use 'degit'

if [[ ! -e "$ZIM_HOME/zimfw.zsh" ]]; then
  command curl -fsSL --create-dirs -o "$ZIM_HOME/zimfw.zsh" \
    https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

if [[ ! "$ZIM_HOME/init.zsh" -nt "${ZIM_CONFIG_FILE:-${ZDOTDIR:-$HOME}/.zimrc}" ]]; then
  source "$ZIM_HOME/zimfw.zsh" init -q
fi

source "$ZIM_HOME/init.zsh"

# --------------------------------------------------------------------------------------------------
# prompt
# --------------------------------------------------------------------------------------------------
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# --------------------------------------------------------------------------------------------------
# shell options
# --------------------------------------------------------------------------------------------------
setopt INTERACTIVE_COMMENTS
setopt NO_CLOBBER
setopt LONG_LIST_JOBS

# --------------------------------------------------------------------------------------------------
# history
# --------------------------------------------------------------------------------------------------
HISTSIZE=20000
SAVEHIST=10000

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt SHARE_HISTORY

alias h='fc -il'

# --------------------------------------------------------------------------------------------------
# editor
# --------------------------------------------------------------------------------------------------
export EDITOR=nano

# --------------------------------------------------------------------------------------------------
# navigation
# --------------------------------------------------------------------------------------------------
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME

alias ..='cd ..'
alias ...='cd ../..'
alias -- -='cd -'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

d() {
  dirs -v | command head -n 10
}

cdr() {
  local root

  root=$(command git rev-parse --show-toplevel 2>/dev/null) || return 1
  cd "$root" || return 1
}

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
fi

# --------------------------------------------------------------------------------------------------
# less
# --------------------------------------------------------------------------------------------------
export PAGER=less
export LESS='FRSj2x2'

export LESS_TERMCAP_mb=$'\E[1;31m'  # Begins blinking.
export LESS_TERMCAP_md=$'\E[1;31m'  # Begins bold.
export LESS_TERMCAP_me=$'\E[0m'     # Ends mode.
export LESS_TERMCAP_ue=$'\E[0m'     # Ends underline.
export LESS_TERMCAP_us=$'\E[1;32m'  # Begins underline.

if [[ $TERM_PROGRAM == vscode ]]; then
  export GIT_PAGER=cat
fi

# --------------------------------------------------------------------------------------------------
# ls
# --------------------------------------------------------------------------------------------------
if (( $+commands[dircolors] )) && command ls --version &>/dev/null; then
  # GNU
  export LS_COLORS='di=1;34:ln=35:so=32:pi=33:ex=31:bd=1;36:cd=1;33:su=30;41:sg=30;46:tw=30;42:ow=30;43'
  alias ls='ls --group-directories-first --color=auto'
else
  # BSD
  export CLICOLOR=1
  export LSCOLORS=ExfxcxdxbxGxDxabagacad
fi

alias l='ls -CF'
alias ll='ls -lh'
alias la='ls -lAh'

# --------------------------------------------------------------------------------------------------
# grep
# --------------------------------------------------------------------------------------------------
export GREP_COLOR='37;45'              # BSD
export GREP_COLORS="mt=${GREP_COLOR}"  # GNU

if (( $+commands[ggrep] )); then
  alias grep='ggrep --color=auto'
elif command grep --version &>/dev/null; then
  alias grep='grep --color=auto'
fi

# --------------------------------------------------------------------------------------------------
# bat
# --------------------------------------------------------------------------------------------------
if (( $+commands[bat] )); then
  export MANROFFOPT="-c"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# --------------------------------------------------------------------------------------------------
# fzf
# --------------------------------------------------------------------------------------------------
if (( $+commands[fzf] )); then
  export FZF_DEFAULT_OPTS='--cycle --layout=reverse --border --height=50%'

  if (( $+commands[fd] )); then
    export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --exclude .git --exclude node_modules'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d --strip-cwd-prefix --hidden --exclude .git --exclude node_modules'

    _fzf_compgen_path() {
      fd --type f --type d --hidden --exclude .git --exclude node_modules . "$1"
    }

    _fzf_compgen_dir() {
      fd --type d --hidden --exclude .git --exclude node_modules . "$1"
    }
  fi

  if (( $+commands[bat] )); then
    export FZF_CTRL_T_OPTS="--bind ctrl-/:toggle-preview --preview 'bat -pp --color=always --line-range :500 {}'"
  fi

  if (( $+commands[tree] )); then
    export FZF_ALT_C_OPTS="--bind ctrl-/:toggle-preview --preview 'tree -C -L 2 --dirsfirst --gitignore {}'"
  fi

  source <(fzf --zsh)
fi

# --------------------------------------------------------------------------------------------------
# fnm
# --------------------------------------------------------------------------------------------------
if (( $+commands[fnm] )); then
  eval "$(fnm env --corepack-enabled --use-on-cd)" >/dev/null 2>&1
fi

# --------------------------------------------------------------------------------------------------
# yandex-cloud
# --------------------------------------------------------------------------------------------------
if [[ -f "$HOME/yandex-cloud/path.bash.inc" ]]; then
  source "$HOME/yandex-cloud/path.bash.inc"
fi

if [[ -f "$HOME/yandex-cloud/completion.zsh.inc" ]]; then
  source "$HOME/yandex-cloud/completion.zsh.inc"
fi

# --------------------------------------------------------------------------------------------------
# aliases
# --------------------------------------------------------------------------------------------------
alias headers='http --print=Hh'
alias listening='sudo lsof -iTCP -sTCP:LISTEN -n -P'

# --------------------------------------------------------------------------------------------------
# local
# --------------------------------------------------------------------------------------------------
[[ -f "$HOME/.zshrc.local.zsh" ]] && source "$HOME/.zshrc.local.zsh"
